# 配置端口
server:
  port: 8080
dubbo:
  # 配置服务信息
  application:
    name: dubbo-consumer
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://47.98.179.202:8848
  # 设置超时时间
  consumer:
    timeout: 4000